export const projects = [
  {
    title: 'NextJS Redux-Saga Website',
    description: 'A real estate website built with NextJS, Redux and Redux-Saga. The third party API used is Bayut by Api Dojo from Rapid API. ',
      image: '/images/1.png',
      tags: ['JavaScript', 'React.js', 'Next.js', 'Redux', 'Chakra UI'],
    source: 'https://github.com/vennson/project-nextjs-redux-saga',
    visit: 'https://nextjs-reduxsaga.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Stream Twilio Chat Web App',
    description:'A full-stack and real time chat application for general purposes. Stream and Twilio is used for the backend.',
    image: '/images/2.png',
    tags: ['JavaScript', 'React.js', 'Node.js', 'Stream', 'Twilio'],
    source: 'https://github.com/vennson/project-medical-pager',
    visit: 'https://medical-pager-vennson.netlify.app/',
    id: 1,
  },
  {
    title: 'Philippines\' Top Google Searches 2004 - 2020',
    description:'A Tableau map graph showing the top google searches in each region in the Philippines from 2004 to 2020. The data is from Google Trends.',
    image: '/images/3.png',
    tags: ['Tableau', 'Google Trends', 'Google Sheet'],
    source: 'https://public.tableau.com/app/profile/frozen3618/viz/Book1s_16147339241920/Sheet1',
    visit: 'https://public.tableau.com/app/profile/frozen3618/viz/Book1s_16147339241920/Sheet1',
    id: 2,
  },
  {
    title: 'South Korea\'s Top Google Searches 2004 - 2020',
    description:'A Tableau map graph showing the top google searches in each region in the South Korea from 2004 to 2020. The data is from Google Trends.',
    image: '/images/4.png',
    tags: ['Tableau', 'Google Trends', 'Google Sheet'],
    source: 'https://public.tableau.com/app/profile/frozen3618/viz/Book1_16132891420790/Sheet1',
    visit: 'https://public.tableau.com/app/profile/frozen3618/viz/Book1_16132891420790/Sheet1',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 'Mar 2015', text: 'Qualified as a DOST-SEI Scholar', },
  { year: 'June 2015', text: 'Highest grade in Computer Programming in class', },
  { year: 'Jan 2020', text: 'Started learning Python then Machine Learning', },
  { year: 'Mar 2020', text: 'Made my first Machine Learning prototype, an AI-powered traffic light network', },
  { year: 'Apr 2020', text: 'Won as a country finalist in a national tech competition', },
  { year: 'May 2020', text: 'Started learning C# then Java', },
  { year: 'Sep 2020', text: 'Graduated from BS in Mechanical Engineering', },
  { year: 'Nov 2020', text: 'Started learning JavaScript, React, then NodeJS', },
  { year: 'Jan 2021', text: 'Landed in IT as my first job', },
];